modLoader="javafml"
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]]
modId="techniq"
version="${file.jarVersion}"
displayName="Techniq"
logoFile=""
credits=""
authors="Entisy"
description='''
'''
#[[dependencies.techniq]]
#    modId="forge"
#    mandatory=true
#    versionRange="[36,)"
#    ordering="NONE"
#    side="BOTH"
#[[dependencies.techniq]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.16.5,1.17)"
#    ordering="NONE"
#    side="BOTH"
